// Generated by Copilot
// Walidatory dla kalkulatora
import { z } from 'zod';

export const calculatorSchema = z.object({
    a: z.number(),
    b: z.number()
});

export const singleNumberSchema = z.object({
    number: z.number().positive()
});
