// Generated by Copilot
// Konfiguracja aplikacji
import { config } from 'dotenv';

config();

export const CONFIG = {
    port: process.env.PORT || 3000,
    apiKey: process.env.API_KEY || '12345_Secret_key',
    nodeEnv: process.env.NODE_ENV || 'development'
} as const;
